#!/bin/sh


# this works, so just storing it here for now
# mogrify -resize 240x240^ -gravity Center -crop 240x240+0+0 +repage -quality 100 -path resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ original-clip-frames-timestamps-12s-14s-20fps/*.png


# use 3 bits per pixel / 8 colors

./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-001.png 2 >../dist/h1.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-002.png 2 >../dist/h2.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-003.png 2 >../dist/h3.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-004.png 2 >../dist/h4.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-005.png 2 >../dist/h5.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-006.png 2 >../dist/h6.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-007.png 2 >../dist/h7.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-008.png 2 >../dist/h8.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-009.png 2 >../dist/h9.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-010.png 2 >../dist/h10.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-011.png 2 >../dist/h11.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-012.png 2 >../dist/h12.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-013.png 2 >../dist/h13.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-014.png 2 >../dist/h14.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-015.png 2 >../dist/h15.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-016.png 2 >../dist/h16.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-017.png 2 >../dist/h17.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-018.png 2 >../dist/h18.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-019.png 2 >../dist/h19.py
./imgtobitmap.py ../media/resized-20-frames-correct-aspect-ratio-lower-quality-10-percent/ezgif-frame-020.png 2 >../dist/h20.py
